### ISSUE TITLE
可以贴一下post请求路径中的内容吗

### ISSUE THREAD

**Issue by zyb955140** [qizikd/usdtwallet#1]

**Comment by qizikd** [comment]
你说的是广播交易，post的内容？

**Comment by zyb955140** [comment]
> 你说的是广播交易，发布的内容？

是的，我看你代码中post和get方法路径都是添加的文件夹路径，可以把文件夹贴一下吗，因为不知道是什么格式

**Comment by qizikd** [comment]
Post /tx/send
Content-Type=application/json
body
{
   " rawtx" : "0x112124545"
}

**Comment by zyb955140** [comment]
> Post /tx/send
> Content-Type=application/json
> body
> {
> " rawtx" : "0x112124545"
> }

app.post('/md5/wallet/usdt/sendto',jsonParser, function (req, res, next) {	
	logger.info("转账Url",req.url)
	console.log("转账Url",req.url)	
这里面的路径不是文件夹路径吗

**Comment by qizikd** [comment]
你这nodejs基础太差了，先去看看express这个怎么用的再说吧
